spring.datasource.url=jdbc:postgresql://localhost:5432/altus
spring.datasource.username=postgres
spring.datasource.password=mktplc10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.thymeleaf.cache=false