-- =========================
-- TABELA ESTADO
-- =========================
CREATE TABLE estado (
   codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nome VARCHAR(100) NOT NULL,
   sigla VARCHAR(2) NOT NULL UNIQUE
);

-- =========================
-- TABELA CIDADE
-- =========================
CREATE TABLE cidade (
   codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   codigo_ibge VARCHAR(7) NOT NULL,
   nome VARCHAR(100) NOT NULL,
   codigo_estado BIGINT NOT NULL,
   CONSTRAINT fk_cidade_estado FOREIGN KEY (codigo_estado) REFERENCES estado(codigo),
   CONSTRAINT unique_cidade UNIQUE (nome, codigo_estado)
);

-- =========================
-- TABELA EMPRESA
-- =========================
CREATE TABLE empresa (
  codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social VARCHAR(100) NOT NULL,
  nome_fantasia VARCHAR(100) NOT NULL,
  cnpj VARCHAR(14) NOT NULL UNIQUE,
  inscricao_estadual VARCHAR(13),
  inscricao_municipal VARCHAR(14),
  data_abertura TIMESTAMP,
  regime_tributario VARCHAR(20),

  logradouro VARCHAR(255),
  numero VARCHAR(10),
  complemento VARCHAR(255),
  cep VARCHAR(8),
  bairro VARCHAR(100),

  codigo_cidade BIGINT,

  email VARCHAR(50) NOT NULL UNIQUE,
  telefone VARCHAR(11),
  celular VARCHAR(11),
  site VARCHAR(100),
  limite_funcionarios INTEGER,
  ativo BOOLEAN DEFAULT TRUE,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_empresa_cidade
    FOREIGN KEY (codigo_cidade) REFERENCES cidade(codigo)
);