-- =========================
-- TABELA ESTADO
-- =========================
CREATE TABLE estado (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nome VARCHAR(100) NOT NULL,
   sigla VARCHAR(2) NOT NULL UNIQUE
);


-- =========================
-- TABELA CIDADE
-- =========================
CREATE TABLE cidade (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   codigo_ibge VARCHAR(7) NOT NULL,
   nome VARCHAR(100) NOT NULL,
   estado_id BIGINT NOT NULL,
   CONSTRAINT fk_cidade_estado FOREIGN KEY (estado_id) REFERENCES estado(id),
   CONSTRAINT unique_cidade UNIQUE (nome, estado_id)
);

-- =========================
-- TABELA EMPRESA
-- =========================
CREATE TABLE empresa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social VARCHAR(100) NOT NULL,
  nome_fantasia VARCHAR(100) NOT NULL,
  cnpj VARCHAR(14) NOT NULL UNIQUE,
  inscricao_estadual VARCHAR(13),
  data_abertura DATE,
  regime_tributario VARCHAR(16) NOT NULL,
  tipo VARCHAR(6) NOT NULL,
  logradouro VARCHAR(150),
  numero VARCHAR(10),
  complemento VARCHAR(150),
  cep VARCHAR(8),
  bairro VARCHAR(100),
  cidade_id BIGINT,
  email VARCHAR(50) NOT NULL,
  telefone VARCHAR(11),
  celular VARCHAR(11),
  site VARCHAR(100),
  ativo BOOLEAN DEFAULT TRUE NOT NULL,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_empresa_cidade FOREIGN KEY (cidade_id) REFERENCES cidade(id)
);

-- =========================
-- TABELA DEPARTAMENTO
-- =========================
CREATE TABLE departamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT fk_departamento_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================
-- TABELA CARGO
-- =========================
CREATE TABLE cargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    salario_base NUMERIC(10,2)
);

-- =========================
-- TABELA FUNCIONARIO
-- =========================
CREATE TABLE funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    nome_social VARCHAR(80),
    telefone VARCHAR(11) NOT NULL,
    email VARCHAR(80) UNIQUE,
    data_nascimento DATE NOT NULL,
    sexo VARCHAR(9) NOT NULL,
    estado_civil VARCHAR(20) NOT NULL,
    nome_mae VARCHAR(80) NOT NULL,
    nome_pai VARCHAR(80),
    telefone_contato_emergencia VARCHAR(11),
    nome_contato_emergencia VARCHAR(80),
    -- Endereço (Embedded)
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    complemento VARCHAR(255),
    bairro VARCHAR(50),
    cep VARCHAR(8),
    cidade_id BIGINT,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    rg VARCHAR(20) NOT NULL,
    pis VARCHAR(11),
    titulo_eleitor VARCHAR(13),
    carteira_trabalho VARCHAR(50),
    nacionalidade VARCHAR(100),
    naturalidade VARCHAR(100),
	empresa_id BIGINT NOT NULL,
    jornada_trabalho VARCHAR(100),
    situacao VARCHAR(50),
    observacoes TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_funcionario_cidade  FOREIGN KEY (cidade_id) REFERENCES cidade(id),
    CONSTRAINT fk_funcionario_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);


-- =========================
-- CONTRATO DE TRABALHO
-- =========================
CREATE TABLE contrato_trabalho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT NOT NULL,
    tipo VARCHAR(15), -- CLT, PJ, Estágio
    data_admissao DATE,
    salario NUMERIC(10,2),
    carga_horaria INT,
    data_fim DATE,
    status VARCHAR(20),
    CONSTRAINT fk_contrato_trabalho_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionario(id)
);

-- =========================
-- LOTAÇÃO (histórico)
-- =========================
CREATE TABLE lotacao_funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT NOT NULL,
    departamento_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL,
    data_inicio DATE,
    data_fim DATE,
    CONSTRAINT fk_lotacao_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionario(id),
    CONSTRAINT fk_lotacao_departamento FOREIGN KEY (departamento_id) REFERENCES departamento(id),
    CONSTRAINT fk_lotacao_cargo FOREIGN KEY (cargo_id) REFERENCES cargo(id)
);

-- =========================
-- ÍNDICES NAS FKs
-- =========================
CREATE INDEX idx_cidade_estado ON cidade(estado_id);
CREATE INDEX idx_empresa_cidade ON empresa(cidade_id);
CREATE INDEX idx_funcionario_cidade ON funcionario(cidade_id);
CREATE INDEX idx_funcionario_empresa ON funcionario(empresa_id);
CREATE INDEX idx_departamento_empresa ON departamento(empresa_id);
CREATE INDEX idx_contrato_funcionario ON contrato_trabalho(funcionario_id);
CREATE INDEX idx_lotacao_funcionario ON lotacao_funcionario(funcionario_id);
CREATE UNIQUE INDEX uk_lotacao_ativa ON lotacao_funcionario(funcionario_id) WHERE data_fim IS NULL;
CREATE UNIQUE INDEX uk_contrato_ativo ON contrato_trabalho(funcionario_id) WHERE data_fim IS NULL;